### ISSUE TITLE
[Question] Values in CatchPokemonMessage

### ISSUE THREAD

**Issue by vankxr** [AeonLucid/POGOProtos#225]
Hello,

Can someone tell me what are the ranges for CatchPokemonMessage values, like reticle size, spin modifier, etc...

I tried to randomize them (Math.random() \* VALUE_SET_BEFORE) and the result was a status_code = 3 (bad request) in the ResponseEnvelop

Thank you :)

**Comment by Grover-c13** [comment]
this.normalizedHitPosition = 1.0; - betwen 0 and 1.0, where the pokemon was hit (normalized because pokeman have different sizes)
this.normalizedReticleSize = 1.95 + Math.random() \* 0.05; between 0 and 2.00, the size of the circle (the larger the smaller the circle, so the size is 2.00-normalizedReticleSize)
this.spinModifier = 0.85 + Math.random() \* 0.15; (between 0 and 1.00)

**Comment by vankxr** [comment]
Thank you :D

**Comment by AeonLucid** [comment]
Closing this issue.
